# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(598, 1024)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 600, 1024))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("#scan_qr\n"
"{\n"
"    background-color: #FFFFFE;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.main_menu = QtWidgets.QWidget()
        self.main_menu.setStyleSheet("#main_menu\n"
"{\n"
"background-image: url(:/image/UTELocker Welcome.png);\n"
"}")
        self.main_menu.setObjectName("main_menu")
        self.bt_code = QtWidgets.QPushButton(self.main_menu)
        self.bt_code.setGeometry(QtCore.QRect(40, 591, 520, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_code.sizePolicy().hasHeightForWidth())
        self.bt_code.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.bt_code.setFont(font)
        self.bt_code.setStyleSheet("#bt_code\n"
"{\n"
"    border-radius: 34px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 17pt; font-weight: bold;\n"
"}\n"
"#bt_code:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.bt_code.setIconSize(QtCore.QSize(16, 16))
        self.bt_code.setObjectName("bt_code")
        self.bt_qr = QtWidgets.QPushButton(self.main_menu)
        self.bt_qr.setGeometry(QtCore.QRect(40, 881, 520, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_qr.sizePolicy().hasHeightForWidth())
        self.bt_qr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.bt_qr.setFont(font)
        self.bt_qr.setStyleSheet("#bt_qr\n"
"{\n"
"    border-radius: 34px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 17pt; font-weight: bold;\n"
"}\n"
"#bt_qr:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.bt_qr.setIconSize(QtCore.QSize(16, 16))
        self.bt_qr.setObjectName("bt_qr")
        self.ad_label = QtWidgets.QLabel(self.main_menu)
        self.ad_label.setGeometry(QtCore.QRect(0, 0, 600, 250))
        self.ad_label.setObjectName("ad_label")
        self.stackedWidget.addWidget(self.main_menu)
        self.widget = QtWidgets.QWidget()
        self.widget.setStyleSheet("#enter_code\n"
"{\n"
"    background-color: #FFFFFE;\n"
"}")
        self.widget.setObjectName("widget")
        self.bt9 = QtWidgets.QPushButton(self.widget)
        self.bt9.setGeometry(QtCore.QRect(370, 600, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt9.sizePolicy().hasHeightForWidth())
        self.bt9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt9.setFont(font)
        self.bt9.setStyleSheet("#btDel:pressed {\n"
"                background-color: #fffffe; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.bt9.setObjectName("bt9")
        self.bt2 = QtWidgets.QPushButton(self.widget)
        self.bt2.setGeometry(QtCore.QRect(240, 760, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt2.sizePolicy().hasHeightForWidth())
        self.bt2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt2.setFont(font)
        self.bt2.setObjectName("bt2")
        self.bt1 = QtWidgets.QPushButton(self.widget)
        self.bt1.setGeometry(QtCore.QRect(110, 760, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt1.sizePolicy().hasHeightForWidth())
        self.bt1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt1.setFont(font)
        self.bt1.setObjectName("bt1")
        self.bt3 = QtWidgets.QPushButton(self.widget)
        self.bt3.setGeometry(QtCore.QRect(370, 760, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt3.sizePolicy().hasHeightForWidth())
        self.bt3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt3.setFont(font)
        self.bt3.setObjectName("bt3")
        self.bt7 = QtWidgets.QPushButton(self.widget)
        self.bt7.setGeometry(QtCore.QRect(110, 600, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt7.sizePolicy().hasHeightForWidth())
        self.bt7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt7.setFont(font)
        self.bt7.setIconSize(QtCore.QSize(16, 16))
        self.bt7.setObjectName("bt7")
        self.btSao = QtWidgets.QPushButton(self.widget)
        self.btSao.setGeometry(QtCore.QRect(110, 840, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSao.sizePolicy().hasHeightForWidth())
        self.btSao.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btSao.setFont(font)
        self.btSao.setObjectName("btSao")
        self.bt6 = QtWidgets.QPushButton(self.widget)
        self.bt6.setGeometry(QtCore.QRect(370, 680, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt6.sizePolicy().hasHeightForWidth())
        self.bt6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.bt6.setFont(font)
        self.bt6.setObjectName("bt6")
        self.btDel = QtWidgets.QPushButton(self.widget)
        self.btDel.setGeometry(QtCore.QRect(370, 840, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btDel.sizePolicy().hasHeightForWidth())
        self.btDel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btDel.setFont(font)
        self.btDel.setObjectName("btDel")
        self.bt0 = QtWidgets.QPushButton(self.widget)
        self.bt0.setGeometry(QtCore.QRect(240, 840, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt0.sizePolicy().hasHeightForWidth())
        self.bt0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt0.setFont(font)
        self.bt0.setObjectName("bt0")
        self.bt8 = QtWidgets.QPushButton(self.widget)
        self.bt8.setGeometry(QtCore.QRect(240, 600, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt8.sizePolicy().hasHeightForWidth())
        self.bt8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt8.setFont(font)
        self.bt8.setObjectName("bt8")
        self.bt4 = QtWidgets.QPushButton(self.widget)
        self.bt4.setGeometry(QtCore.QRect(110, 680, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt4.sizePolicy().hasHeightForWidth())
        self.bt4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt4.setFont(font)
        self.bt4.setObjectName("bt4")
        self.bt5 = QtWidgets.QPushButton(self.widget)
        self.bt5.setGeometry(QtCore.QRect(240, 680, 120, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt5.sizePolicy().hasHeightForWidth())
        self.bt5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.bt5.setFont(font)
        self.bt5.setObjectName("bt5")
        self.btSubmit = QtWidgets.QPushButton(self.widget)
        self.btSubmit.setGeometry(QtCore.QRect(220, 410, 160, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btSubmit.sizePolicy().hasHeightForWidth())
        self.btSubmit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btSubmit.setFont(font)
        self.btSubmit.setStyleSheet("#btSubmit\n"
"{\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 12pt; font-weight: bold;\n"
"}\n"
"#btSubmit:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.btSubmit.setIconSize(QtCore.QSize(16, 16))
        self.btSubmit.setObjectName("btSubmit")
        self.bt_back_enter_code = QtWidgets.QPushButton(self.widget)
        self.bt_back_enter_code.setGeometry(QtCore.QRect(5, -5, 61, 41))
        self.bt_back_enter_code.setStyleSheet("#bt_back_enter_code\n"
"{\n"
"    background-image: url(:/image/bt_back.png);\n"
"    border-radius: 1px;\n"
"}\n"
"#bt_back_enter_code:pressed\n"
"{\n"
"    border-radius: 1px;\n"
"}")
        self.bt_back_enter_code.setText("")
        self.bt_back_enter_code.setObjectName("bt_back_enter_code")
        self.textEdit = QtWidgets.QTextEdit(self.widget)
        self.textEdit.setGeometry(QtCore.QRect(142, 240, 316, 70))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.textEdit.setFont(font)
        self.textEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEdit.setStyleSheet("QTextEdit \n"
"{\n"
"    border: 2px solid #000000;\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    padding-left: 26px;\n"
"    background-color: #ffffff;\n"
"    text-align: center;\n"
"    letter-spacing: 20px;\n"
"}\n"
"QTextEdit::verticalScrollBar,\n"
"            QTextEdit::horizontalScrollBar {\n"
"                width: 0;\n"
"            }\n"
"QTextEdit::cursor {\n"
"                width: 2px;\n"
"                background-color: red;\n"
"                margin-left: 30px; /* Khoảng cách từ mép trái */\n"
"            }\n"
"")
        self.textEdit.setInputMethodHints(QtCore.Qt.ImhMultiLine)
        self.textEdit.setFrameShape(QtWidgets.QFrame.Box)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.textEdit.setObjectName("textEdit")
        self.waiting_msg = QtWidgets.QLabel(self.widget)
        self.waiting_msg.setEnabled(True)
        self.waiting_msg.setGeometry(QtCore.QRect(130, -50, 341, 191))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.waiting_msg.setFont(font)
        self.waiting_msg.setStyleSheet("#waiting_msg {\n"
"    width: 300px; /* Đặt chiều rộng cho label */\n"
"    height: 201px; /* Đặt chiều cao cho label */\n"
"    border-radius: 15px;\n"
"    padding: 0 30px 0 30px; /* 0 phía trên, 5px phía trái và phải, 0 phía dưới */\n"
"    background-color: #DCF2F1;\n"
"    text-align: center;\n"
"    color: #000000;\n"
"    font: 14pt \"Calibri\";\n"
"    padding-bottom: 90px; /* Khoảng cách 20px từ trên cùng */\n"
"}")
        self.waiting_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.waiting_msg.setObjectName("waiting_msg")
        self.confirm_popup = QtWidgets.QFrame(self.widget)
        self.confirm_popup.setGeometry(QtCore.QRect(60, -60, 501, 281))
        self.confirm_popup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.confirm_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.confirm_popup.setObjectName("confirm_popup")
        self.confirm_msg = QtWidgets.QLabel(self.confirm_popup)
        self.confirm_msg.setEnabled(True)
        self.confirm_msg.setGeometry(QtCore.QRect(30, 30, 441, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.confirm_msg.setFont(font)
        self.confirm_msg.setStyleSheet("#confirm_msg {\n"
"    width: 300px; /* Đặt chiều rộng cho label */\n"
"    height: 201px; /* Đặt chiều cao cho label */\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px 0 20px; /* 0 phía trên, 5px phía trái và phải, 0 phía dưới */\n"
"    background-color: #DCF2F1;\n"
"    text-align: center;\n"
"    color: #000000;\n"
"    font: 14pt \"Calibri\";\n"
"    padding-bottom: 90px; /* Khoảng cách 20px từ trên cùng */\n"
"}")
        self.confirm_msg.setText("")
        self.confirm_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.confirm_msg.setWordWrap(True)
        self.confirm_msg.setObjectName("confirm_msg")
        self.btConfirm = QtWidgets.QPushButton(self.confirm_popup)
        self.btConfirm.setGeometry(QtCore.QRect(170, 200, 160, 50))
        self.btConfirm.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btConfirm.setStyleSheet("#btConfirm\n"
"{\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 12pt; font-weight: bold;\n"
"}\n"
"#btSubmit:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.btConfirm.setObjectName("btConfirm")
        self.wrong_pass_label = QtWidgets.QLabel(self.widget)
        self.wrong_pass_label.setGeometry(QtCore.QRect(30, 520, 541, 41))
        self.wrong_pass_label.setStyleSheet("#wrong_pass_label\n"
"{\n"
"    font: 14pt \"Calibri\";\n"
"    color: \"red\"\n"
"}")
        self.wrong_pass_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wrong_pass_label.setWordWrap(False)
        self.wrong_pass_label.setObjectName("wrong_pass_label")
        self.btOpenAll = QtWidgets.QPushButton(self.widget)
        self.btOpenAll.setGeometry(QtCore.QRect(90, 410, 160, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btOpenAll.sizePolicy().hasHeightForWidth())
        self.btOpenAll.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btOpenAll.setFont(font)
        self.btOpenAll.setStyleSheet("#btOpenAll\n"
"{\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 12pt; font-weight: bold;\n"
"}\n"
"#btOpenAll:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.btOpenAll.setIconSize(QtCore.QSize(16, 16))
        self.btOpenAll.setObjectName("btOpenAll")
        self.admin_popup = QtWidgets.QFrame(self.widget)
        self.admin_popup.setGeometry(QtCore.QRect(60, 550, 501, 281))
        self.admin_popup.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.admin_popup.setFrameShadow(QtWidgets.QFrame.Raised)
        self.admin_popup.setObjectName("admin_popup")
        self.admin_msg = QtWidgets.QLabel(self.admin_popup)
        self.admin_msg.setEnabled(True)
        self.admin_msg.setGeometry(QtCore.QRect(20, 30, 441, 241))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.admin_msg.setFont(font)
        self.admin_msg.setStyleSheet("#admin_msg {\n"
"    width: 300px; /* Đặt chiều rộng cho label */\n"
"    height: 201px; /* Đặt chiều cao cho label */\n"
"    border-radius: 15px;\n"
"    padding: 10px 20px 0 20px; /* 0 phía trên, 5px phía trái và phải, 0 phía dưới */\n"
"    background-color: #DCF2F1;\n"
"    text-align: center;\n"
"    color: #000000;\n"
"    font: 14pt \"Calibri\";\n"
"    padding-bottom: 90px; /* Khoảng cách 20px từ trên cùng */\n"
"}")
        self.admin_msg.setAlignment(QtCore.Qt.AlignCenter)
        self.admin_msg.setWordWrap(True)
        self.admin_msg.setObjectName("admin_msg")
        self.btGotIt = QtWidgets.QPushButton(self.admin_popup)
        self.btGotIt.setGeometry(QtCore.QRect(170, 200, 160, 50))
        self.btGotIt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btGotIt.setStyleSheet("#btGotIt\n"
"{\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 12pt; font-weight: bold;\n"
"}\n"
"#btGotIt:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.btGotIt.setObjectName("btGotIt")
        self.btOpenLock = QtWidgets.QPushButton(self.widget)
        self.btOpenLock.setGeometry(QtCore.QRect(330, 320, 160, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btOpenLock.sizePolicy().hasHeightForWidth())
        self.btOpenLock.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btOpenLock.setFont(font)
        self.btOpenLock.setStyleSheet("#btOpenLock\n"
"{\n"
"    border-radius: 10px;\n"
"    padding: 5px;\n"
"    background-color: #0b9964;\n"
"    color: #ffffff;\n"
"    text-align: center;\n"
"    font-family: Arial; font-size: 12pt; font-weight: bold;\n"
"}\n"
"#btOpenLock:pressed {\n"
"                background-color: #ffffff; /* Màu nền khi nút được nhấn */\n"
"            }")
        self.btOpenLock.setIconSize(QtCore.QSize(16, 16))
        self.btOpenLock.setObjectName("btOpenLock")
        self.stackedWidget.addWidget(self.widget)
        self.scan_qr = QtWidgets.QWidget()
        self.scan_qr.setStyleSheet("#scan_qr\n"
"{\n"
"    \n"
"    background-image: url(:/image/QR_UNLOCK.png);\n"
"}")
        self.scan_qr.setObjectName("scan_qr")
        self.bt_back_scan_qr = QtWidgets.QPushButton(self.scan_qr)
        self.bt_back_scan_qr.setGeometry(QtCore.QRect(5, -5, 61, 41))
        self.bt_back_scan_qr.setStyleSheet("#bt_back_scan_qr\n"
"{\n"
"    \n"
"    background-image: url(:/image/bt_back.png);\n"
"    border-radius: 1px;\n"
"}\n"
"#bt_back_scan_qr:pressed\n"
"{\n"
"    border-radius: 1px;\n"
"}")
        self.bt_back_scan_qr.setText("")
        self.bt_back_scan_qr.setObjectName("bt_back_scan_qr")
        self.stackedWidget.addWidget(self.scan_qr)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_code.setText(_translate("MainWindow", "Enter"))
        self.bt_qr.setText(_translate("MainWindow", "Scan"))
        self.ad_label.setText(_translate("MainWindow", "TextLabel"))
        self.bt9.setText(_translate("MainWindow", "9"))
        self.bt2.setText(_translate("MainWindow", "2"))
        self.bt1.setText(_translate("MainWindow", "1"))
        self.bt3.setText(_translate("MainWindow", "3"))
        self.bt7.setText(_translate("MainWindow", "7"))
        self.btSao.setText(_translate("MainWindow", "*"))
        self.bt6.setText(_translate("MainWindow", "6"))
        self.btDel.setText(_translate("MainWindow", "DEL"))
        self.bt0.setText(_translate("MainWindow", "0"))
        self.bt8.setText(_translate("MainWindow", "8"))
        self.bt4.setText(_translate("MainWindow", "4"))
        self.bt5.setText(_translate("MainWindow", "5"))
        self.btSubmit.setText(_translate("MainWindow", "Submit"))
        self.textEdit.setPlaceholderText(_translate("MainWindow", " ------"))
        self.waiting_msg.setText(_translate("MainWindow", "Please wait a moment..."))
        self.btConfirm.setText(_translate("MainWindow", "Confirm"))
        self.wrong_pass_label.setText(_translate("MainWindow", "We couldn\'t find a locker corresponding to your code"))
        self.btOpenAll.setText(_translate("MainWindow", "Open All"))
        self.admin_msg.setText(_translate("MainWindow", "WELCOME TO THE ADMIN MODE!\n"
" Enter the locker number you wish to open and press the \'Submit\' button.\n"
" If you want to open all lockers, press the \'Open All\' button"))
        self.btGotIt.setText(_translate("MainWindow", "Got It!"))
        self.btOpenLock.setText(_translate("MainWindow", "SUBMIT"))
import image_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
